<a href="https://colab.research.google.com/github/Ujjawal19Shahi/AI-in-Data-Science/blob/main/PLOTY_IN_PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import plotly.express as px
import pandas as pd
import matplotlib.pyplot as plt
from re import template

In [2]:
data=px.data.gapminder()
data

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [3]:
data=px.data.gapminder()
data.query('country == "India"')

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
696,India,Asia,1952,37.373,372000000,546.565749,IND,356
697,India,Asia,1957,40.249,409000000,590.061996,IND,356
698,India,Asia,1962,43.605,454000000,658.347151,IND,356
699,India,Asia,1967,47.193,506000000,700.770611,IND,356
700,India,Asia,1972,50.651,567000000,724.032527,IND,356
701,India,Asia,1977,54.208,634000000,813.337323,IND,356
702,India,Asia,1982,56.596,708000000,855.723538,IND,356
703,India,Asia,1987,58.553,788000000,976.512676,IND,356
704,India,Asia,1992,60.223,872000000,1164.406809,IND,356
705,India,Asia,1997,61.765,959000000,1458.817442,IND,356
706,India,Asia,2002,62.879,1034172547,1746.769454,IND,356
707,India,Asia,2007,64.698,1110396331,2452.210407,IND,356

In [4]:
data=px.data.gapminder()
india_data = data.query('country == "India"')
fig = px.bar(india_data, x='year', y='pop', title='Population by India', labels={'pop':'Population'}, color='year', hover_data=['pop'], text='pop')
fig.update_traces(texttemplate='%{text:.2s}', textposition='inside')
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
fig.update_layout(xaxis_title='year',yaxis_title='population',xaxis_tickangle=-45,yaxis_tickangle=-45,template="plotly_dark")
fig.show()

In [5]:
data=px.data.gapminder()
india_data = data.query('country == "India"')
fig = px.line(india_data, x='year', y='pop', title='Population by India', labels={'pop':'Population'}, color='year', hover_data=['pop'], text='pop')
fig.update_traces( texttemplate='%{text:.2s}',textposition='top center')
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
fig.update_layout(xaxis_title='year',yaxis_title='population',xaxis_tickangle=-45,yaxis_tickangle=-45,template="plotly_dark")
fig.show()

In [6]:
data=px.data.gapminder()
india_data = data.query('country == "India"')
fig = px.scatter(india_data, x='gdpPercap', y='lifeExp', title='GDP per Capital in India', labels={'gdpPercap':'GDP per Capital'}, color='gdpPercap', hover_data=['gdpPercap'], text='gdpPercap')
fig.update_traces(texttemplate='%{text:.2s}', textposition='top center')
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
fig.update_layout(xaxis_title='gdpPercap',yaxis_title='lifeExp',xaxis_tickangle=-45,yaxis_tickangle=-45,template="plotly_dark")
fig.show()

In [7]:
data=px.data.gapminder()
india_data = data.query('country == "India"')
fig = px.pie(india_data,  values='gdpPercap', names='year', title='GDP per Capital in India', labels={'gdpPercap':'GDP per Capital'}, color='gdpPercap', hover_data=['gdpPercap'])
fig.update_traces( textposition='inside')
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
fig.show()

In [8]:
data=px.data.gapminder()
india_data = data.query('country == "India"')
fig = px.histogram(india_data, x='year', y='pop', title='Population by India', labels={'pop':'Population'}, color='year', hover_data=['pop'])
fig.update_traces( textposition='inside')
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
fig.update_layout(xaxis_title='year',yaxis_title='population',xaxis_tickangle=-45,yaxis_tickangle=-45,template="plotly_dark")
fig.show()

In [9]:
data=px.data.gapminder()
india_data = data.query('country == "India"')
fig = px.density_heatmap(india_data, x='year', y='pop', title='Population by India', labels={'pop':'Population'}, hover_data=['pop'])
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
fig.update_layout(xaxis_title='year',yaxis_title='population',xaxis_tickangle=-45,yaxis_tickangle=-45,template="plotly_dark")
fig.show()

In [12]:
data=px.data.gapminder()
india_data = data.query('country == "India"')
fig = px.box(india_data,y='lifeExp',points="all",color_discrete_sequence=["red"])
fig.update_traces(boxmean=False,jitter=0.6,marker=dict(size=2,opacity=0.6))
fig.show()